language: cpp
os: linux

matrix:
  include:
    - env: OSX=10.11
      os: osx
      osx_image: osx10.11
    - env: OSX=10.10
      os: osx
      osx_image: xcode7
    - env: OSX=10.9
      os: osx
      osx_image: beta-xcode6.2
    - os: linux

before_install: cd coin-or/Dip && ./get.depencies.svn.sh

install: ./configure && make install

script: make test
