language: cpp
os: linux

matrix:
  include:
    - env: OSX=10.11
      os: osx
      osx_image: osx10.11
    - env: OSX=10.10
      os: osx
      osx_image: xcode7
    - env: OSX=10.9
      os: osx
      osx_image: beta-xcode6.2
    - os: linux

before_install: ./get.dependencies.svn.sh

install: ./configure && make install > /dev/null

script: make test
